// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configuration;
using Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configurations;
using Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Fields;
using Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Item;
using Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Search;
using Soenneker.ProductBoard.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Fixed.Entities
{
    /// <summary>
    /// Builds and executes requests for operations under \fixed\entities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configuration property</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The configurations property</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configurations.ConfigurationsRequestBuilder Configurations
        {
            get => new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Configurations.ConfigurationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fields property</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Fields.FieldsRequestBuilder Fields
        {
            get => new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Fields.FieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.ProductBoard.OpenApiClient.fixed.entities.item collection</summary>
        /// <param name="position">Entity identifier.</param>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Item.EntitiesItemRequestBuilder"/></returns>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Item.EntitiesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.Item.EntitiesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/entities{?archived*,fields%5B%5D*,name*,owner%5Bemail%5D*,owner%5Bid%5D*,pageCursor*,parent%5Bid%5D*,status%5Bid%5D*,status%5Bname%5D*,type%5B%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fixed/entities{?archived*,fields%5B%5D*,name*,owner%5Bemail%5D*,owner%5Bid%5D*,pageCursor*,parent%5Bid%5D*,status%5Bid%5D*,status%5Bname%5D*,type%5B%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a paginated list of Entities.You can filter results, sort them, and control which fields are returned.&gt; Without the `members:pii:read` scope, owner email fields are returned as `[redacted]`. Filtering by `owner[email]` requires the `members:pii:read` scope. Without the `users:pii:read` scope, user entity name and email fields are returned as `[redacted]`.Use the `type[]` query parameter to filter by one or more entity types (e.g. `type[]=feature&amp;type[]=initiative`).Use the `fields` parameter to request only the fields you need.## Filter availabilityNot all filters apply to all entity types. For example, `status` filtering is only availablefor types that have a status field (e.g. `feature`, `initiative`), and `parent[id]` only worksfor types that have a parent relationship.Use `GET /v2/entities/configurations/{type}` to check which filters are supported for a specific type.The `filters` array in the configuration response lists all available filter parameters,their exact query parameter names, and value schemas.## Limitations- Only the `AND` operator is supported when applying multiple filters. `OR`, `NOT`, or nested conditions are not supported.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 408 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder.EntitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder.EntitiesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "408", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesGetResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Entities of the specified type.  You must specify the `type` (e.g. `feature`, `initiative`) and provide required fields based on your workspace configuration.Use the `/configuration` endpoint to discover what fields are available and required.## Limitations- The field names and availability depend on your workspace setup.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 408 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostResponse?> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostResponse> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "408", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.ProductBoard.OpenApiClient.Models.EntitiesErrorResponse1.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a paginated list of Entities.You can filter results, sort them, and control which fields are returned.&gt; Without the `members:pii:read` scope, owner email fields are returned as `[redacted]`. Filtering by `owner[email]` requires the `members:pii:read` scope. Without the `users:pii:read` scope, user entity name and email fields are returned as `[redacted]`.Use the `type[]` query parameter to filter by one or more entity types (e.g. `type[]=feature&amp;type[]=initiative`).Use the `fields` parameter to request only the fields you need.## Filter availabilityNot all filters apply to all entity types. For example, `status` filtering is only availablefor types that have a status field (e.g. `feature`, `initiative`), and `parent[id]` only worksfor types that have a parent relationship.Use `GET /v2/entities/configurations/{type}` to check which filters are supported for a specific type.The `filters` array in the configuration response lists all available filter parameters,their exact query parameter names, and value schemas.## Limitations- Only the `AND` operator is supported when applying multiple filters. `OR`, `NOT`, or nested conditions are not supported.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder.EntitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder.EntitiesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new Entities of the specified type.  You must specify the `type` (e.g. `feature`, `initiative`) and provide required fields based on your workspace configuration.Use the `/configuration` endpoint to discover what fields are available and required.## Limitations- The field names and availability depend on your workspace setup.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ProductBoard.OpenApiClient.Fixed.Entities.EntitiesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a paginated list of Entities.You can filter results, sort them, and control which fields are returned.&gt; Without the `members:pii:read` scope, owner email fields are returned as `[redacted]`. Filtering by `owner[email]` requires the `members:pii:read` scope. Without the `users:pii:read` scope, user entity name and email fields are returned as `[redacted]`.Use the `type[]` query parameter to filter by one or more entity types (e.g. `type[]=feature&amp;type[]=initiative`).Use the `fields` parameter to request only the fields you need.## Filter availabilityNot all filters apply to all entity types. For example, `status` filtering is only availablefor types that have a status field (e.g. `feature`, `initiative`), and `parent[id]` only worksfor types that have a parent relationship.Use `GET /v2/entities/configurations/{type}` to check which filters are supported for a specific type.The `filters` array in the configuration response lists all available filter parameters,their exact query parameter names, and value schemas.## Limitations- Only the `AND` operator is supported when applying multiple filters. `OR`, `NOT`, or nested conditions are not supported.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EntitiesRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by archived status (true/false)</summary>
            [QueryParameter("archived")]
            public bool? Archived { get; set; }
            /// <summary>&quot;Controls which fields are returned in the response to optimize bandwidth and tailor data to your needs.**Options:**- Not specified: Returns only fields with non-empty values (default)- `fields[]=all`: Returns all fields, including those with `null` values- `fields[]=name&amp;fields[]=status`: Returns only the specified fieldsFor detailed usage, examples, and field discovery, see [Response Field Control](https://developer.productboard.com/v2.0.0/reference/response-field-control).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("fields%5B%5D")]
            public string[]? Fields { get; set; }
#nullable restore
#else
            [QueryParameter("fields%5B%5D")]
            public string[] Fields { get; set; }
#endif
            /// <summary>Filter by entity name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Filter by owner email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("owner%5Bemail%5D")]
            public string? Owneremail { get; set; }
#nullable restore
#else
            [QueryParameter("owner%5Bemail%5D")]
            public string Owneremail { get; set; }
#endif
            /// <summary>Filter by owner ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("owner%5Bid%5D")]
            public string? Ownerid { get; set; }
#nullable restore
#else
            [QueryParameter("owner%5Bid%5D")]
            public string Ownerid { get; set; }
#endif
            /// <summary>Cursor for pagination. Use the value from `links.next` to fetch the next page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pageCursor")]
            public string? PageCursor { get; set; }
#nullable restore
#else
            [QueryParameter("pageCursor")]
            public string PageCursor { get; set; }
#endif
            /// <summary>Filter by parent PM entity ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parent%5Bid%5D")]
            public string? Parentid { get; set; }
#nullable restore
#else
            [QueryParameter("parent%5Bid%5D")]
            public string Parentid { get; set; }
#endif
            /// <summary>Filter by status ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status%5Bid%5D")]
            public string? Statusid { get; set; }
#nullable restore
#else
            [QueryParameter("status%5Bid%5D")]
            public string Statusid { get; set; }
#endif
            /// <summary>Filter by status name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status%5Bname%5D")]
            public string? Statusname { get; set; }
#nullable restore
#else
            [QueryParameter("status%5Bname%5D")]
            public string Statusname { get; set; }
#endif
            /// <summary>&quot;Filter by one or more entity types. Use array notation: `type[]=feature&amp;type[]=initiative`.Currently supported PM entity types:  - product  - component  - feature  - subfeature  - initiative  - objective  - keyResult  - release  - releaseGroup  - user  - companyThe exact types available may vary based on the configuration of the workspace.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type%5B%5D")]
            public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2[]? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type%5B%5D")]
            public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2[] Type { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
