// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models.Notes
{
    /// <summary>
    /// The company to be associated with the note.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Model_Company : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Domain of a company the note (and possibly a user) should be linked to.This attribute cannot be combined with the `id` attribute.This attribute is currently meant exclusively to substitute the default Company domain extraction mechanism (based on the domain part of an email address) when identifying a user via `user.external_id` only.Therefore, it can&apos;t be combined with any email field - in that case the Company domain is extracted automatically from given email address.The Company resolution mechanism based on `company.domain` works as follows:- If only `company.domain` is provided that doesn&apos;t match any existing Company within Productboard, a new Company is created and the note is linked to that Company.- If only `company.domain` is provided that matches an existing Company within Productboard, the note is linked to that Company.- If both `user.external_id` and `company.domain` are provided and the user identified by given external ID is already linked to a Company, then given `company.domain` must match the domain of that Company.- If both `user.external_id` and `company.domain` are provided and the user identified by given external ID is not linked to a Company and given Company domain matches existing Company in Productboard, then the user is linked to the Company.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>This attribute signifies a source record ID for a Company object in PB.The ID is imported from external tools such as Salesforce, and uniquely identifies the company within the system.When present, the system first attempts to match a company based on this external_id.If no match is found, the system continues to search by domain.This external_id is saved within the Company entity upon its creation or update, provided the existing Company record associated with the given domain does not already contain an external_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The id of the company.This attribute cannot be combined with the `domain` attribute.</summary>
        public Guid? Id { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Notes.Model_Company"/> and sets the default values.
        /// </summary>
        public Model_Company()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Notes.Model_Company"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.Notes.Model_Company CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.Notes.Model_Company();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteGuidValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
