// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.MergedOpenapi.Fixed.Notes.Item.Relationships
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTargetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "company")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "feature")]
        #pragma warning disable CS1591
        Feature,
        #pragma warning restore CS1591
        [EnumMember(Value = "subfeature")]
        #pragma warning disable CS1591
        Subfeature,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
        [EnumMember(Value = "component")]
        #pragma warning disable CS1591
        Component,
        #pragma warning restore CS1591
    }
}
