// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ProductBoard.OpenApiClient.Models.Releases;
using Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.ReleaseGroups
{
    /// <summary>
    /// Builds and executes requests for operations under \release-groups
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReleaseGroupsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ProductBoard.OpenApiClient.releaseGroups.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.Item.ReleaseGroupsItemRequestBuilder"/></returns>
        public global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.Item.ReleaseGroupsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.Item.ReleaseGroupsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleaseGroupsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/release-groups", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleaseGroupsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/release-groups", rawUrl)
        {
        }
        /// <summary>
        /// Returns detail of all release groups.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` link in the response to fetch the next page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsGetResponse?> GetAsReleaseGroupsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsGetResponse> GetAsReleaseGroupsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsGetResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns detail of all release groups.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` link in the response to fetch the next page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 400 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsReleaseGroupsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new release group.You can create new release groups only if you are on Scale or Enterprise plan and you have *Multiple release groups* enabled.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostResponse?> PostAsReleaseGroupsPostResponseAsync(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostResponse> PostAsReleaseGroupsPostResponseAsync(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new release group.You can create new release groups only if you are on Scale or Enterprise plan and you have *Multiple release groups* enabled.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors">When receiving a 403 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsReleaseGroupsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse?> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.ProductBoard.OpenApiClient.Models.Releases.Error_ApiErrors.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns detail of all release groups.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` link in the response to fetch the next page.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new release group.You can create new release groups only if you are on Scale or Enterprise plan and you have *Multiple release groups* enabled.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ProductBoard.OpenApiClient.ReleaseGroups.ReleaseGroupsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReleaseGroupsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReleaseGroupsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
