// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Operation with a value (addItems, removeItems, set)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_merged_openapi_TeamPatchOperationMember1 : IParsable
    {
        /// <summary>The operation type.</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_op? Op { get; set; }
        /// <summary>The field to operate on.</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_path? Path { get; set; }
        /// <summary>Member references for the operation.Each item must include either `id` (space membership UUID) or `email`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value>? Value { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value> Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "op", n => { Op = n.GetEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_op>(); } },
                { "path", n => { Path = n.GetEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_path>(); } },
                { "value", n => { Value = n.GetCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value>(global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_op>("op", Op);
            writer.WriteEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_path>("path", Path);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value>("value", Value);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class C_merged_openapi_TeamPatchOperationMember1_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1? CMergedOpenapiTeamPatchOperationMember1ValueMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1 CMergedOpenapiTeamPatchOperationMember1ValueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2? CMergedOpenapiTeamPatchOperationMember1ValueMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2 CMergedOpenapiTeamPatchOperationMember1ValueMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1.C_merged_openapi_TeamPatchOperationMember1_value();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CMergedOpenapiTeamPatchOperationMember1ValueMember1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CMergedOpenapiTeamPatchOperationMember1ValueMember2 = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CMergedOpenapiTeamPatchOperationMember1ValueMember1 != null)
                {
                    return CMergedOpenapiTeamPatchOperationMember1ValueMember1.GetFieldDeserializers();
                }
                else if(CMergedOpenapiTeamPatchOperationMember1ValueMember2 != null)
                {
                    return CMergedOpenapiTeamPatchOperationMember1ValueMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CMergedOpenapiTeamPatchOperationMember1ValueMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember1>(null, CMergedOpenapiTeamPatchOperationMember1ValueMember1);
                }
                else if(CMergedOpenapiTeamPatchOperationMember1ValueMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_merged_openapi_TeamPatchOperationMember1_valueMember2>(null, CMergedOpenapiTeamPatchOperationMember1ValueMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
