// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_plugin_integrations_ConnectionState : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState? CPluginIntegrationsConnectedState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState CPluginIntegrationsConnectedState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState? CPluginIntegrationsErrorState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState CPluginIntegrationsErrorState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState? CPluginIntegrationsInitialConnectionState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState CPluginIntegrationsInitialConnectionState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState? CPluginIntegrationsProgressState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState CPluginIntegrationsProgressState { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectionState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectionState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectionState();
            if("C_plugin_integrations_ConnectedState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CPluginIntegrationsConnectedState = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState();
            }
            else if("C_plugin_integrations_ErrorState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CPluginIntegrationsErrorState = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState();
            }
            else if("C_plugin_integrations_InitialConnectionState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CPluginIntegrationsInitialConnectionState = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState();
            }
            else if("C_plugin_integrations_ProgressState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CPluginIntegrationsProgressState = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CPluginIntegrationsConnectedState != null)
            {
                return CPluginIntegrationsConnectedState.GetFieldDeserializers();
            }
            else if(CPluginIntegrationsErrorState != null)
            {
                return CPluginIntegrationsErrorState.GetFieldDeserializers();
            }
            else if(CPluginIntegrationsInitialConnectionState != null)
            {
                return CPluginIntegrationsInitialConnectionState.GetFieldDeserializers();
            }
            else if(CPluginIntegrationsProgressState != null)
            {
                return CPluginIntegrationsProgressState.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CPluginIntegrationsConnectedState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ConnectedState>(null, CPluginIntegrationsConnectedState);
            }
            else if(CPluginIntegrationsErrorState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ErrorState>(null, CPluginIntegrationsErrorState);
            }
            else if(CPluginIntegrationsInitialConnectionState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_InitialConnectionState>(null, CPluginIntegrationsInitialConnectionState);
            }
            else if(CPluginIntegrationsProgressState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_plugin_integrations_ProgressState>(null, CPluginIntegrationsProgressState);
            }
        }
    }
}
#pragma warning restore CS0618
