// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class C_teams_TeamPatchOperation : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1? CTeamsTeamPatchOperationMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1 CTeamsTeamPatchOperationMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2? CTeamsTeamPatchOperationMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2 CTeamsTeamPatchOperationMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperation();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CTeamsTeamPatchOperationMember1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CTeamsTeamPatchOperationMember2 = new global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CTeamsTeamPatchOperationMember1 != null)
            {
                return CTeamsTeamPatchOperationMember1.GetFieldDeserializers();
            }
            else if(CTeamsTeamPatchOperationMember2 != null)
            {
                return CTeamsTeamPatchOperationMember2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CTeamsTeamPatchOperationMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember1>(null, CTeamsTeamPatchOperationMember1);
            }
            else if(CTeamsTeamPatchOperationMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.C_teams_TeamPatchOperationMember2>(null, CTeamsTeamPatchOperationMember2);
            }
        }
    }
}
#pragma warning restore CS0618
