// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CMergedOpenapiTeamMemberResourceFieldsName : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper? CMergedOpenapiTeamsObfuscatedValueWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper CMergedOpenapiTeamsObfuscatedValueWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch? MergedOpenapiUnionBranch { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch MergedOpenapiUnionBranch { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamMemberResourceFieldsName"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamMemberResourceFieldsName CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamMemberResourceFieldsName();
            result.CMergedOpenapiTeamsObfuscatedValueWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper();
            result.MergedOpenapiUnionBranch = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CMergedOpenapiTeamsObfuscatedValueWrapper != null || MergedOpenapiUnionBranch != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CMergedOpenapiTeamsObfuscatedValueWrapper, MergedOpenapiUnionBranch);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamsObfuscatedValueWrapper>(null, CMergedOpenapiTeamsObfuscatedValueWrapper, MergedOpenapiUnionBranch);
        }
    }
}
#pragma warning restore CS0618
