// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Fields of a member resource.Note: When the `members:pii:read` scope is not present, the `name`, `username` and `email`fields will return `[redacted]` instead of actual values.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CMergedOpenapiMemberFields1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the member is disabled.</summary>
        public bool? Disabled { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email? Email { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email Email { get; set; }
#endif
        /// <summary>Whether the member has a pending invitation that has not yet been accepted.</summary>
        public bool? InvitationPending { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name Name { get; set; }
#endif
        /// <summary>Role of the member in the workspace.</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1_role? Role { get; set; }
        /// <summary>List of teams the member belongs to. Always included in the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamReference1>? Teams { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamReference1> Teams { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username? Username { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1"/> and sets the default values.
        /// </summary>
        public CMergedOpenapiMemberFields1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disabled", n => { Disabled = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email>(global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email.CreateFromDiscriminatorValue); } },
                { "invitationPending", n => { InvitationPending = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name>(global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name.CreateFromDiscriminatorValue); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1_role>(); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamReference1>(global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamReference1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "username", n => { Username = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username>(global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("disabled", Disabled);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email>("email", Email);
            writer.WriteBoolValue("invitationPending", InvitationPending);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name>("name", Name);
            writer.WriteEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1_role>("role", Role);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiTeamReference1>("teams", Teams);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username>("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CMergedOpenapiMemberFields1_email : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1? CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1 CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1? MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1 MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_email();
                result.CMergedOpenapiObfuscatedValueWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1();
                result.MergedOpenapiMergedOpenapiUnionBranch1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CMergedOpenapiObfuscatedValueWrapper1 != null || MergedOpenapiMergedOpenapiUnionBranch1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1>(null, CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CMergedOpenapiMemberFields1_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1? CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1 CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1? MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1 MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_name();
                result.CMergedOpenapiObfuscatedValueWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1();
                result.MergedOpenapiMergedOpenapiUnionBranch1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CMergedOpenapiObfuscatedValueWrapper1 != null || MergedOpenapiMergedOpenapiUnionBranch1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1>(null, CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CMergedOpenapiMemberFields1_username : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1? CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1 CMergedOpenapiObfuscatedValueWrapper1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1? MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1 MergedOpenapiMergedOpenapiUnionBranch1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiMemberFields1.CMergedOpenapiMemberFields1_username();
                result.CMergedOpenapiObfuscatedValueWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1();
                result.MergedOpenapiMergedOpenapiUnionBranch1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiUnionBranch1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CMergedOpenapiObfuscatedValueWrapper1 != null || MergedOpenapiMergedOpenapiUnionBranch1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.CMergedOpenapiObfuscatedValueWrapper1>(null, CMergedOpenapiObfuscatedValueWrapper1, MergedOpenapiMergedOpenapiUnionBranch1);
            }
        }
    }
}
#pragma warning restore CS0618
