// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeatureUpdateRequestDeprecated : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Feature archived flag value or `null` if it should not be changed.</summary>
        public bool? Archived { get; set; }
        /// <summary>New feature description or `null` if it should not be changed. The format is a limited subset of HTML defined by [this XML schema](https://developer.productboard.com/page/schema). Check out the [Rich Text section](https://developer.productboard.com/reference/rich-text-formatting) for more information on what tags can be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>New feature name or `null` if it should not be changed. Note that empty string `&quot;&quot;` is allowed and actually means to set the name to an empty value as opposed to `null`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>New parent of the feature or `null` if it should not be changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent Parent { get; set; }
#endif
        /// <summary>New feature status or `null` if it should not be changed. It is not possible to specify both ID and name, only one of them can be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_status? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_status Status { get; set; }
#endif
        /// <summary>Feature timeframe.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_timeframe? Timeframe { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_timeframe Timeframe { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated"/> and sets the default values.
        /// </summary>
        public FeatureUpdateRequestDeprecated()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent>(global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_status>(global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_status.CreateFromDiscriminatorValue); } },
                { "timeframe", n => { Timeframe = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_timeframe>(global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_timeframe.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated_timeframe>("timeframe", Timeframe);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FeatureUpdateRequestDeprecated_parent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper? ComponentIdWrapper { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper ComponentIdWrapper { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper? FeatureIdWrapper { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper FeatureIdWrapper { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper? ProductIdWrapper { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper ProductIdWrapper { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureUpdateRequestDeprecated.FeatureUpdateRequestDeprecated_parent();
                if("ComponentIdWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ComponentIdWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper();
                }
                else if("FeatureIdWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FeatureIdWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper();
                }
                else if("ProductIdWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProductIdWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ComponentIdWrapper != null)
                {
                    return ComponentIdWrapper.GetFieldDeserializers();
                }
                else if(FeatureIdWrapper != null)
                {
                    return FeatureIdWrapper.GetFieldDeserializers();
                }
                else if(ProductIdWrapper != null)
                {
                    return ProductIdWrapper.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ComponentIdWrapper != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ComponentIdWrapper>(null, ComponentIdWrapper);
                }
                else if(FeatureIdWrapper != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FeatureIdWrapper>(null, FeatureIdWrapper);
                }
                else if(ProductIdWrapper != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ProductIdWrapper>(null, ProductIdWrapper);
                }
            }
        }
    }
}
#pragma warning restore CS0618
