// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Filter criteria for the entity search.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FixedEntitySearchFilter_2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A date range filter with optional `from` and `to` bounds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2? CreatedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2 CreatedAt { get; set; }
#endif
        /// <summary>Filters applied to entity field values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFieldFilters_2? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFieldFilters_2 Fields { get; set; }
#endif
        /// <summary>Filter by entity IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Id { get; set; }
#nullable restore
#else
        public List<Guid?> Id { get; set; }
#endif
        /// <summary>Filters applied to entity metadata (not yet active).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchMetadataFilter_2? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchMetadataFilter_2 Metadata { get; set; }
#endif
        /// <summary>Filters applied to entity relationships.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchRelationshipFilters_2? Relationships { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchRelationshipFilters_2 Relationships { get; set; }
#endif
        /// <summary>Filter by one or more entity types. If empty or not provided, searches across all entity types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2?>? Type { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2?> Type { get; set; }
#endif
        /// <summary>A date range filter with optional `from` and `to` bounds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2? UpdatedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2 UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFilter_2"/> and sets the default values.
        /// </summary>
        public FixedEntitySearchFilter_2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFilter_2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFilter_2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFilter_2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2>(global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2.CreateFromDiscriminatorValue); } },
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFieldFilters_2>(global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFieldFilters_2.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchMetadataFilter_2>(global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchMetadataFilter_2.CreateFromDiscriminatorValue); } },
                { "relationships", n => { Relationships = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchRelationshipFilters_2>(global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchRelationshipFilters_2.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetCollectionOfEnumValues<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2>()?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2>(global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2>("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchFieldFilters_2>("fields", Fields);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("id", Id);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchMetadataFilter_2>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntitySearchRelationshipFilters_2>("relationships", Relationships);
            writer.WriteCollectionOfEnumValues<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedEntityType_2>("type", Type);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.FixedDateRangeFilter_2>("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
