// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>Additional format hint for the value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FixedConfigurationFilterSchema_3_format
    {
        [EnumMember(Value = "uuid")]
        #pragma warning disable CS1591
        Uuid,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "date-time")]
        #pragma warning disable CS1591
        DateTime,
        #pragma warning restore CS1591
    }
}
