// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Relationship filters. Multiple values use OR logic within a relationship type.Different relationship types use AND logic.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MergedOpenapiNoteSearchFilterRelationships_1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Filter by customer (user or company). Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer? Customer { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer Customer { get; set; }
#endif
        /// <summary>Filter by linked feature. Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link? Link { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link Link { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1"/> and sets the default values.
        /// </summary>
        public MergedOpenapiNoteSearchFilterRelationships_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customer", n => { Customer = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer.CreateFromDiscriminatorValue); } },
                { "link", n => { Link = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer>("customer", Customer);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link>("link", Link);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MergedOpenapiNoteSearchFilterRelationships_1_customer : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1? MergedOpenapiRelationshipFilterValue1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1 MergedOpenapiRelationshipFilterValue1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1? MergedOpenapiUnionBranch1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1 MergedOpenapiUnionBranch1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_customer();
                if("MergedOpenapiRelationshipFilterValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiRelationshipFilterValue1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1();
                }
                else if("MergedOpenapiUnionBranch_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiUnionBranch1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiRelationshipFilterValue1 != null)
                {
                    return MergedOpenapiRelationshipFilterValue1.GetFieldDeserializers();
                }
                else if(MergedOpenapiUnionBranch1 != null)
                {
                    return MergedOpenapiUnionBranch1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiRelationshipFilterValue1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1>(null, MergedOpenapiRelationshipFilterValue1);
                }
                else if(MergedOpenapiUnionBranch1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1>(null, MergedOpenapiUnionBranch1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MergedOpenapiNoteSearchFilterRelationships_1_link : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1? MergedOpenapiRelationshipFilterValue1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1 MergedOpenapiRelationshipFilterValue1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1? MergedOpenapiUnionBranch1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1 MergedOpenapiUnionBranch1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiNoteSearchFilterRelationships_1.MergedOpenapiNoteSearchFilterRelationships_1_link();
                if("MergedOpenapiRelationshipFilterValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiRelationshipFilterValue1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1();
                }
                else if("MergedOpenapiUnionBranch_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiUnionBranch1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiRelationshipFilterValue1 != null)
                {
                    return MergedOpenapiRelationshipFilterValue1.GetFieldDeserializers();
                }
                else if(MergedOpenapiUnionBranch1 != null)
                {
                    return MergedOpenapiUnionBranch1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiRelationshipFilterValue1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiRelationshipFilterValue_1>(null, MergedOpenapiRelationshipFilterValue1);
                }
                else if(MergedOpenapiUnionBranch1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiUnionBranch_1>(null, MergedOpenapiUnionBranch1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
