// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>The mode of work progress calculation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_fixed_WorkProgressModeEnum
    {
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
        [EnumMember(Value = "statusBased")]
        #pragma warning disable CS1591
        StatusBased,
        #pragma warning restore CS1591
        [EnumMember(Value = "calculated")]
        #pragma warning disable CS1591
        Calculated,
        #pragma warning restore CS1591
    }
}
