// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Filter by note field values
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MergedOpenapiMergedOpenapiNoteSearchFilterFields_1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Filter by archived status</summary>
        public bool? Archived { get; set; }
        /// <summary>Filter by creator. Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator? Creator { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator Creator { get; set; }
#endif
        /// <summary>Filter by owner. Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner Owner { get; set; }
#endif
        /// <summary>Filter by processed status</summary>
        public bool? Processed { get; set; }
        /// <summary>Filter by tag. Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag? Tag { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag Tag { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1"/> and sets the default values.
        /// </summary>
        public MergedOpenapiMergedOpenapiNoteSearchFilterFields_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator.CreateFromDiscriminatorValue); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner.CreateFromDiscriminatorValue); } },
                { "processed", n => { Processed = n.GetBoolValue(); } },
                { "tag", n => { Tag = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator>("creator", Creator);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner>("owner", Owner);
            writer.WriteBoolValue("processed", Processed);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag>("tag", Tag);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1? MergedOpenapiMergedOpenapiMemberFilterValue1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1 MergedOpenapiMergedOpenapiMemberFilterValue1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1? UnionBranchWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1 UnionBranchWrapper1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_creator();
                if("MergedOpenapiMergedOpenapiMemberFilterValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiMergedOpenapiMemberFilterValue1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1();
                }
                else if("UnionBranchWrapper_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnionBranchWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiMergedOpenapiMemberFilterValue1 != null)
                {
                    return MergedOpenapiMergedOpenapiMemberFilterValue1.GetFieldDeserializers();
                }
                else if(UnionBranchWrapper1 != null)
                {
                    return UnionBranchWrapper1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiMergedOpenapiMemberFilterValue1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1>(null, MergedOpenapiMergedOpenapiMemberFilterValue1);
                }
                else if(UnionBranchWrapper1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1>(null, UnionBranchWrapper1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1? MergedOpenapiMergedOpenapiMemberFilterValue1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1 MergedOpenapiMergedOpenapiMemberFilterValue1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1? UnionBranchWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1 UnionBranchWrapper1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_owner();
                if("MergedOpenapiMergedOpenapiMemberFilterValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiMergedOpenapiMemberFilterValue1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1();
                }
                else if("UnionBranchWrapper_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnionBranchWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiMergedOpenapiMemberFilterValue1 != null)
                {
                    return MergedOpenapiMergedOpenapiMemberFilterValue1.GetFieldDeserializers();
                }
                else if(UnionBranchWrapper1 != null)
                {
                    return UnionBranchWrapper1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiMergedOpenapiMemberFilterValue1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMemberFilterValue_1>(null, MergedOpenapiMergedOpenapiMemberFilterValue1);
                }
                else if(UnionBranchWrapper1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1>(null, UnionBranchWrapper1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1? MergedOpenapiMergedOpenapiTagFilterValue1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1 MergedOpenapiMergedOpenapiTagFilterValue1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1? UnionBranchWrapper1 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1 UnionBranchWrapper1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1.MergedOpenapiMergedOpenapiNoteSearchFilterFields_1_tag();
                if("MergedOpenapiMergedOpenapiTagFilterValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiMergedOpenapiTagFilterValue1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1();
                }
                else if("UnionBranchWrapper_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnionBranchWrapper1 = new global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiMergedOpenapiTagFilterValue1 != null)
                {
                    return MergedOpenapiMergedOpenapiTagFilterValue1.GetFieldDeserializers();
                }
                else if(UnionBranchWrapper1 != null)
                {
                    return UnionBranchWrapper1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiMergedOpenapiTagFilterValue1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiTagFilterValue_1>(null, MergedOpenapiMergedOpenapiTagFilterValue1);
                }
                else if(UnionBranchWrapper1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranchWrapper_1>(null, UnionBranchWrapper1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
