// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A collection of fields that can be used to create or update a Note.It is a subset of `NoteFields` that is used for creation or update operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1_fields? Fields { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1_fields Fields { get; set; }
#endif
        /// <summary>&quot;A list of patch operations to perform on a Note field.Each operation can be one of `set`, `clear`, `addItems`, or `removeItems`.**Supported Operations:**- `set`: Set a field to a specific value (supports all fields)- `clear`: Clear/reset a field to its default value (supports owner, tags, content)- `addItems`: Add items to array fields (supports tags, conversation content)- `removeItems`: Remove items from array fields (supports tags, conversation content)**Field-specific support:**- **owner**: set, clear- **tags**: set, clear, addItems, removeItems- **archived**: set- **processed**: set- **name**: set- **content** (textNote): set- **content** (conversationNote): set, addItems, removeItems**Operation Compatibility Rules (for each field):**- Cannot combine `set`/`clear` with `addItems`/`removeItems` operations on the same field- Cannot combine both `set` and `clear` operations on the same field- Can combine `addItems` and `removeItems` together on the same field (for array operations)&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes>? Patch { get; set; }
#nullable restore
#else
        public List<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes> Patch { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1"/> and sets the default values.
        /// </summary>
        public MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fields", n => { Fields = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1_fields>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1_fields.CreateFromDiscriminatorValue); } },
                { "patch", n => { Patch = n.GetCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes>(global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1_fields>("fields", Fields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes>("patch", Patch);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Notes : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1? MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1 MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1? MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1 MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotesUpdateNote1Data_1.Notes();
                if("MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1();
                }
                else if("MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11 = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11 != null)
                {
                    return MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11.GetFieldDeserializers();
                }
                else if(MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11 != null)
                {
                    return MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation1_1>(null, MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperation11);
                }
                else if(MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear1_1>(null, MergedOpenapiMergedOpenapiMergedOpenapiNotePatchOperationClear11);
                }
            }
        }
    }
}
#pragma warning restore CS0618
