// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>Role of the member in the workspace.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Merged_openapi_MemberFields_role
    {
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "maker")]
        #pragma warning disable CS1591
        Maker,
        #pragma warning restore CS1591
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "contributor")]
        #pragma warning disable CS1591
        Contributor,
        #pragma warning restore CS1591
    }
}
