// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// &quot;This patch operation modifies a field value using set, addItems, or removeItems operations.**Operation Types:**- `set`: Replace the entire field value- `addItems`: Add items to array fields (tags, conversation content)- `removeItems`: Remove items from array fields (tags, conversation content)&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Merged_openapi_merged_openapi_NotePatchOperation : IParsable
    {
        /// <summary>The operation to perform on the field.Can be one of `set`, `addItems`, `removeItems`.</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation_op? Op { get; set; }
        /// <summary>&quot;The path to the field to be modified.Common field paths: \&quot;owner\&quot;, \&quot;tags\&quot;, \&quot;archived\&quot;, \&quot;processed\&quot;, \&quot;name\&quot;, \&quot;content\&quot;&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "op", n => { Op = n.GetEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation_op>(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value>(global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation_op>("op", Op);
            writer.WriteStringValue("path", Path);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value>("value", Value);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NoteCreateOrUpdateFieldValue"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Merged_openapi_merged_openapi_NotePatchOperation_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper? MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NoteCreateOrUpdateFieldValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NoteCreateOrUpdateFieldValue? MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NoteCreateOrUpdateFieldValue MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NotePatchOperation.Merged_openapi_merged_openapi_NotePatchOperation_value();
                result.MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper();
                result.MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue = new global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_NoteCreateOrUpdateFieldValue();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper != null || MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper, MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.Merged_openapi_merged_openapi_ConversationNotePartsAssign_Wrapper>(null, MergedOpenapiMergedOpenapiConversationNotePartsAssignWrapper, MergedOpenapiMergedOpenapiNoteCreateOrUpdateFieldValue);
            }
        }
    }
}
#pragma warning restore CS0618
