// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MergedOpenapiConnectionState : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState? MergedOpenapiConnectedState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState MergedOpenapiConnectedState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState? MergedOpenapiErrorState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState MergedOpenapiErrorState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState? MergedOpenapiInitialConnectionState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState MergedOpenapiInitialConnectionState { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState? MergedOpenapiProgressState { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState MergedOpenapiProgressState { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectionState"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectionState CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectionState();
            if("MergedOpenapiConnectedState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiConnectedState = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState();
            }
            else if("MergedOpenapiErrorState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiErrorState = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState();
            }
            else if("MergedOpenapiInitialConnectionState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiInitialConnectionState = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState();
            }
            else if("MergedOpenapiProgressState".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MergedOpenapiProgressState = new global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MergedOpenapiConnectedState != null)
            {
                return MergedOpenapiConnectedState.GetFieldDeserializers();
            }
            else if(MergedOpenapiErrorState != null)
            {
                return MergedOpenapiErrorState.GetFieldDeserializers();
            }
            else if(MergedOpenapiInitialConnectionState != null)
            {
                return MergedOpenapiInitialConnectionState.GetFieldDeserializers();
            }
            else if(MergedOpenapiProgressState != null)
            {
                return MergedOpenapiProgressState.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MergedOpenapiConnectedState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiConnectedState>(null, MergedOpenapiConnectedState);
            }
            else if(MergedOpenapiErrorState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiErrorState>(null, MergedOpenapiErrorState);
            }
            else if(MergedOpenapiInitialConnectionState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiInitialConnectionState>(null, MergedOpenapiInitialConnectionState);
            }
            else if(MergedOpenapiProgressState != null)
            {
                writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.MergedOpenapiProgressState>(null, MergedOpenapiProgressState);
            }
        }
    }
}
#pragma warning restore CS0618
