// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Filter by metadata properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotesNoteSearchFilterMetadata_5 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Filter by source system. Single object or array (OR logic).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source Source { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5"/> and sets the default values.
        /// </summary>
        public NotesNoteSearchFilterMetadata_5()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source>(global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source>("source", Source);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NotesNoteSearchFilterMetadata_5_source : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5? NotesSourceFilterValue5 { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5 NotesSourceFilterValue5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper? UnionBranchWrapper { get; set; }
#nullable restore
#else
            public global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper UnionBranchWrapper { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteSearchFilterMetadata_5.NotesNoteSearchFilterMetadata_5_source();
                if("NotesSourceFilterValue_5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.NotesSourceFilterValue5 = new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5();
                }
                else if("UnionBranch_Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UnionBranchWrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NotesSourceFilterValue5 != null)
                {
                    return NotesSourceFilterValue5.GetFieldDeserializers();
                }
                else if(UnionBranchWrapper != null)
                {
                    return UnionBranchWrapper.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(NotesSourceFilterValue5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.NotesSourceFilterValue_5>(null, NotesSourceFilterValue5);
                }
                else if(UnionBranchWrapper != null)
                {
                    writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.UnionBranch_Wrapper>(null, UnionBranchWrapper);
                }
            }
        }
    }
}
#pragma warning restore CS0618
