// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper"/>, <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteCreateOrUpdateFieldValue_2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotesNotePatchOperation2Value : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper? NotesConversationNotePartsAssign2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper NotesConversationNotePartsAssign2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteCreateOrUpdateFieldValue_2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteCreateOrUpdateFieldValue_2? NotesNoteCreateOrUpdateFieldValue2 { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteCreateOrUpdateFieldValue_2 NotesNoteCreateOrUpdateFieldValue2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNotePatchOperation2Value"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNotePatchOperation2Value CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNotePatchOperation2Value();
            result.NotesConversationNotePartsAssign2Wrapper = new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper();
            result.NotesNoteCreateOrUpdateFieldValue2 = new global::Soenneker.ProductBoard.OpenApiClient.Models.NotesNoteCreateOrUpdateFieldValue_2();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(NotesConversationNotePartsAssign2Wrapper != null || NotesNoteCreateOrUpdateFieldValue2 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NotesConversationNotePartsAssign2Wrapper, NotesNoteCreateOrUpdateFieldValue2);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.NotesConversationNotePartsAssign_2_Wrapper>(null, NotesConversationNotePartsAssign2Wrapper, NotesNoteCreateOrUpdateFieldValue2);
        }
    }
}
#pragma warning restore CS0618
