// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    /// <summary>New release state or missing if it should not be changed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReleaseUpdateRequest_state
    {
        [EnumMember(Value = "upcoming")]
        #pragma warning disable CS1591
        Upcoming,
        #pragma warning restore CS1591
        [EnumMember(Value = "in-progress")]
        #pragma warning disable CS1591
        InProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
    }
}
