// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReleaseUpdateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Archived flag value or missing if it should not be changed.</summary>
        public bool? Archived { get; set; }
        /// <summary>New release description or missing if it should not be changed. The format is a limited subset of HTML defined by [this XML schema](https://developer.productboard.com/page/schema).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>New release name or missing if it should not be changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>New release group or missing if it should not be changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_releaseGroup? ReleaseGroup { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_releaseGroup ReleaseGroup { get; set; }
#endif
        /// <summary>New release state or missing if it should not be changed.</summary>
        public global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_state? State { get; set; }
        /// <summary>Release timeframe.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_timeframe? Timeframe { get; set; }
#nullable restore
#else
        public global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_timeframe Timeframe { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest"/> and sets the default values.
        /// </summary>
        public ReleaseUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "releaseGroup", n => { ReleaseGroup = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_releaseGroup>(global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_releaseGroup.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_state>(); } },
                { "timeframe", n => { Timeframe = n.GetObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_timeframe>(global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_timeframe.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_releaseGroup>("releaseGroup", ReleaseGroup);
            writer.WriteEnumValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_state>("state", State);
            writer.WriteObjectValue<global::Soenneker.ProductBoard.OpenApiClient.Models.ReleaseUpdateRequest_timeframe>("timeframe", Timeframe);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
