// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.ProductBoard.OpenApiClient.KeyResults.Item;
using Soenneker.ProductBoard.OpenApiClient.Models.Common;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.ProductBoard.OpenApiClient.KeyResults
{
    /// <summary>
    /// Builds and executes requests for operations under \key-results
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeyResultsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.ProductBoard.OpenApiClient.keyResults.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.Item.KeyResultsItemRequestBuilder"/></returns>
        public global::Soenneker.ProductBoard.OpenApiClient.KeyResults.Item.KeyResultsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.ProductBoard.OpenApiClient.KeyResults.Item.KeyResultsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeyResultsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/key-results{?archived*,owner%2Eemail*,parent%2Eid*,status%2Eid*,status%2Ename*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeyResultsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/key-results{?archived*,owner%2Eemail*,parent%2Eid*,status%2Eid*,status%2Ename*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns detail of all key results.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` linkin the response to fetch the next page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Common.Error_ApiErrors2">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder.KeyResultsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder.KeyResultsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Common.Error_ApiErrors2.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsGetResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new key result
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.ProductBoard.OpenApiClient.Models.Common.Error_ApiErrors2">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostResponse?> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostResponse> PostAsync(global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.ProductBoard.OpenApiClient.Models.Common.Error_ApiErrors2.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostResponse>(requestInfo, global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns detail of all key results.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` linkin the response to fetch the next page.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder.KeyResultsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder.KeyResultsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new key result
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.ProductBoard.OpenApiClient.KeyResults.KeyResultsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns detail of all key results.This API is paginated, only the first 100 items are returned by default. The client should then recursively follow `links.next` linkin the response to fetch the next page.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeyResultsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by whether entities are archived or not.</summary>
            [QueryParameter("archived")]
            public bool? Archived { get; set; }
            /// <summary>Filter by email of the user owning the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("owner%2Eemail")]
            public string? OwnerEmail { get; set; }
#nullable restore
#else
            [QueryParameter("owner%2Eemail")]
            public string OwnerEmail { get; set; }
#endif
            /// <summary>Filter by id of the parent entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parent%2Eid")]
            public string? ParentId { get; set; }
#nullable restore
#else
            [QueryParameter("parent%2Eid")]
            public string ParentId { get; set; }
#endif
            /// <summary>Filter by status of the entity, where the status is selected by id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status%2Eid")]
            public string? StatusId { get; set; }
#nullable restore
#else
            [QueryParameter("status%2Eid")]
            public string StatusId { get; set; }
#endif
            /// <summary>Filter by status of the entity, where the status is selected by name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status%2Ename")]
            public string? StatusName { get; set; }
#nullable restore
#else
            [QueryParameter("status%2Ename")]
            public string StatusName { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
